##########
# stdout #
##########
13
40
20
10
5
16
8
4
2

##########
# stderr #
##########
================================================================================
voir: An error occurred in an overseer. Execution proceeds as normal.
================================================================================
Traceback (most recent call last):
  <redacted>, in _step_one
    next_phase = gen.send(ph.value)
  <redacted>, in _crash
    raise ValueError("boom.")
ValueError: boom.
================================================================================

##########
#  data  #
##########
{"$event": "phase", "$data": {"name": "init"}}
{"$event": "phase", "$data": {"name": "parse_args"}}
{"$event": "phase", "$data": {"name": "load_script"}}
{"$event": "overseer_error", "$data": {"type": "ValueError", "message": "boom."}}
{"$event": "phase", "$data": {"name": "run_script"}}
{"$event": "phase", "$data": {"name": "finalize"}}

